### ISSUE TITLE
The Add event

### ISSUE THREAD

**Issue by jasongrout** [phosphorjs/phosphor-observablelist#7]
It's confusing that the ListTypeChange.Add event really corresponds to the list's `.insert` function, since it has an index.  In other words, if I wanted to replicate an Add event on another list, I can't use the other list's `.add` method, I have to use `.insert`.  Perhaps the event name could be changed to `Insert`, or `.add` could take an argument?

**Comment by sccolbert** [comment]
There's also asymmetry in `Remove`, which serves for both `remove` and `removeAt` methods. Naming things is hard, and this would be a breaking change for little benefit.

**Comment by jasongrout** [comment]
I think the asymmetry is stronger for `Add` than for remove - if `.insert` was named `.addAt`, it would go better with the `Add` change type.

**Comment by sccolbert** [comment]
I chose names from existing frameworks: https://msdn.microsoft.com/en-us/library/system.collections.specialized.notifycollectionchangedaction(v=vs.110).aspx
